### ISSUE TITLE
Almost all shiny inputs do not render properly

### ISSUE THREAD

**Issue by DivadNojnarg** [RinteRface/shinyF7#1]
This was expected since Framework7 contains its own inputs:

```r
ui <- f7Page(
  checkboxInput("somevalue", "Some value", FALSE),
  verbatimTextOutput("value")
)
server <- function(input, output) {
  output$value <- renderText({ input$somevalue })
}
shinyApp(ui, server)
```

Concerns: radioButtons, checkboxInput, checkboxGroupInput, numericInput, textInput, textAreaInput, dataInput, datRangeInput. 

sliderInput render well since they are not imported from bootstrap but rangeslider...

However, the javascript works...

**Comment by JohnCoene** [comment]
I'm not sure I fully understand. 

If you import bootstrap _after_ `framework7.min.css` it should work as it will override all those classes i.e.: `checkbox` and apply the Bootstrap styles. Even then I'm not sure that is what you want, Framework7 has its own inputs, loading Boostrap will be buggy and look odd.

The input bindings are in `shared/shiny.min.js` hence the input working nonetheless.

The only way I know is to re-implement all of these like we did in `shinybulma`. What do you think?

**Comment by DivadNojnarg** [comment]
This is currently being fixed

**Comment by DivadNojnarg** [comment]
shinyF7 is standalone and has its own inputs and update-input functions, with mobile ready styles... No need to integrate shiny inputs. I close...
