### ISSUE TITLE
[Feature Request] F7 Smart Select input allowing to select multiple

### ISSUE THREAD

**Issue by LucasMelo3** [RinteRface/shinyF7#17]
Dear RinteRface Team,

It would be really good if the F7SmartSelect input could be used to **select more than one item**!

Thank you in advance!

**Comment by DivadNojnarg** [comment]
@LucasMelo3: I actually fixed it but forgot to reference it. Thanks for your feedback :)

**Comment by DivadNojnarg** [comment]
See 2c14537
